### ISSUE TITLE
JDK版本不同导致CommandLineRunner错误

### ISSUE THREAD

**Issue by wooyin** [wh1t3p1g/tabby#20]
使用JDK8u261运行会[CommandLineRunner错误](https://github.com/wh1t3p1g/tabby/issues/9)。
使用JDK8u121运行则没问题，师傅可以自己调一下。

**Comment by wh1t3p1g** [comment]
你好，
可以贴一下错误，我目前没有win的环境

**Comment by wooyin** [comment]
8u121 `java -Xmx6g -jar tabby-1.1.0.RELEASE.jar --isJDKOnly`没问题
8u121 `java -Xmx6g -jar tabby-1.1.0.RELEASE.jar ./lib --isSaveOnly`就报错CommandLineRunner了。

**Comment by wooyin** [comment]
`java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:822) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar!/:2.4.5]
	at tabby.App.main(App.java:43) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_261]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tabby-1.1.0.RELEASE.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [tabby-1.1.0.RELEASE.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tabby-1.1.0.RELEASE.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [tabby-1.1.0.RELEASE.jar:na]
Caused by: java.lang.reflect.UndeclaredThrowableException: null
	at org.springframework.data.neo4j.core.$Proxy103.run(Unknown Source) ~[na:6.0.8]
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$RunnableStatement.runWith(DefaultNeo4jClient.java:160) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:282) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
	at java.util.Optional.flatMap(Optional.java:241) ~[na:1.8.0_261]
	at org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getSingleResult(Neo4jTemplate.java:661) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
	at org.springframework.data.neo4j.repository.query.Neo4jQueryExecution$DefaultQueryExecution.execute(Neo4jQueryExecution.java:53) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
	at org.springframework.data.neo4j.repository.query.AbstractNeo4jQuery.execute(AbstractNeo4jQuery.java:85) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.6.jar!/:5.3.6]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.6.jar!/:5.3.6]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.6.jar!/:5.3.6]
	at com.sun.proxy.$Proxy80.clearAll(Unknown Source) ~[na:na]
	at tabby.dal.neo4j.service.ClassService.clear(ClassService.java:26) ~[classes!/:na]
	at tabby.core.container.DataContainer.save2Neo4j(DataContainer.java:313) ~[classes!/:na]
	at tabby.core.Analyser.save(Analyser.java:128) ~[classes!/:na]
	at tabby.core.Analyser.run(Analyser.java:47) ~[classes!/:na]
	at tabby.App.lambda$run$0(App.java:97) [classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) [spring-boot-2.4.5.jar!/:2.4.5]
	... 13 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_261]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_261]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_261]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_261]
	at org.springframework.data.neo4j.core.DefaultNeo4jClient$AutoCloseableQueryRunnerHandler.invoke(DefaultNeo4jClient.java:108) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
	... 43 common frames omitted
Caused by: org.neo4j.driver.exceptions.AuthenticationException: The client is unauthorized due to authentication failure.
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:143) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:69) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:51) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:37) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
	... 48 common frames omitted
	Suppressed: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database terminated. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.
		at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:53) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:46) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.async.inbound.ChannelErrorHandler.channelInactive(ChannelErrorHandler.java:76) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]
	Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause: null
		at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:72) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:105) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.unpackFailureMessage(MessageReaderV1.java:83) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.messaging.v1.MessageReaderV1.read(MessageReaderV1.java:59) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:83) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:35) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:47) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.1.1.jar!/:4.1.1-eac256ab0fe1a26e16b8c683fb90af7d3e0c471c]
		at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]`

**Comment by wooyin** [comment]
> 你好， 可以贴一下错误，我目前没有win的环境

用的是mbp，自编译jar，jdk8u121和jdk8u261

**Comment by wh1t3p1g** [comment]
看着应该是neo4j数据库认证的问题，check一下neo4j配置的是不是neo4j/password

**Comment by wh1t3p1g** [comment]
> > 你好， 可以贴一下错误，我目前没有win的环境
> 
> 用的是mbp，自编译jar，jdk8u121和jdk8u261

我目前用的openjdk8u292

**Comment by wooyin** [comment]
牛，搞定
