### ISSUE TITLE
分析单个JAR包报错

### ISSUE THREAD

**Issue by cokeBeer** [wh1t3p1g/tabby#28]
调用栈
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-07 18:40:18.371 ERROR 15994 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:822) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar:2.4.5]
	at tabby.App.main(App.java:36) [main/:na]
Caused by: java.lang.RuntimeException: None of the basic classes could be loaded! Check your Soot class path!
	at soot.Scene.loadBasicClasses(Scene.java:1755) ~[soot-4.2.1.jar:na]
	at tabby.core.scanner.ClassInfoScanner.loadAndExtract(ClassInfoScanner.java:55) ~[main/:na]
	at tabby.core.scanner.ClassInfoScanner.run(ClassInfoScanner.java:39) ~[main/:na]
	at tabby.core.Analyser.runSootAnalysis(Analyser.java:107) ~[main/:na]
	at tabby.core.Analyser.run(Analyser.java:81) ~[main/:na]
	at tabby.App.lambda$run$0(App.java:89) [main/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) [spring-boot-2.4.5.jar:2.4.5]
	... 5 common frames omitted
```
配置文件如下，这里设置`excludeJDK=true`，只分析单个JAR包
```
# build code property graph
tabby.build.enable                    = true
# jdk settings
tabby.build.isJDKProcess              = true
tabby.build.withAllJDK                = false
tabby.build.excludeJDK                = true
tabby.build.isJDKOnly                 = false

# dealing fatjar
tabby.build.checkFatJar               = true

# default pointed-to analysis
tabby.build.isFullCallGraphCreate     = false

# targets to analyse
tabby.build.target                    = path/to/target
tabby.build.libraries                 = path/to/lib

# load to neo4j
tabby.load.enable                     = false

# debug
tabby.debug.details                   = false
tabby.debug.inner.details             = false
```

**Comment by cokeBeer** [comment]
一个可能的修复，添加try-catch块，位于`tabby.core.scanner.ClassInfoScanner#loadAndExtract`
```java
    public Map<String, CompletableFuture<ClassReference>> loadAndExtract(List<String> targets){
        Map<String, CompletableFuture<ClassReference>> results = new HashMap<>();
        try{
            Scene.v().loadBasicClasses();
        }catch (Exception e){
            log.warn(e.getMessage());
        }
        Scene.v().loadDynamicClasses();
        ...
    }
```

**Comment by wh1t3p1g** [comment]
排除了jdk后 有没有加入自己特定的jdk的jar包

**Comment by cokeBeer** [comment]
没有

**Comment by wh1t3p1g** [comment]
```
# jdk settings
tabby.build.isJDKProcess              = false
tabby.build.withAllJDK                = false
tabby.build.excludeJDK                = false
tabby.build.isJDKOnly                 = false
```
按我的理解，改成这样就行

**Comment by cokeBeer** [comment]
感谢回答，已解决
