### ISSUE TITLE
储存数据库报错：NULL not allowed for column "IS_OPTIMIZE"

### ISSUE THREAD

**Issue by RicterZ** [wh1t3p1g/tabby#32]
```java
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: NULL not allowed for column "IS_OPTIMIZE"; SQL statement:
insert into call (invoker_type, line_num, polluted_position, real_call_type, source, target, id) values (?, ?, ?, ?, ?, ?, ?) [23502-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:459) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:205) ~[h2-1.4.200.jar!/:na]
	at org.h2.message.DbException.get(DbException.java:181) ~[h2-1.4.200.jar!/:na]
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:374) ~[h2-1.4.200.jar!/:na]
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:845) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.dml.Insert.insertRows(Insert.java:187) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.dml.Insert.update(Insert.java:151) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.CommandContainer.update(CommandContainer.java:198) ~[h2-1.4.200.jar!/:na]
	at org.h2.command.Command.executeUpdate(Command.java:251) ~[h2-1.4.200.jar!/:na]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:191) ~[h2-1.4.200.jar!/:na]
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:152) ~[h2-1.4.200.jar!/:na]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-3.4.5.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar!/:na]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197) ~[hibernate-core-5.4.30.Final.jar!/:5.4.30.Final]
```

**Comment by wh1t3p1g** [comment]
`IS_OPTIMIZE` 是之前遗留的无用参数，最新版剔除了。之前生成的db文件中还带有这个数据会导致无法导入。
1. 删掉原有的db文件
2. build最新版，重新生成

或直接操作db文件删除这一列
