### ISSUE TITLE
win下jar启动报错

### ISSUE THREAD

**Issue by qing-root** [wh1t3p1g/tabby#40]
编译好报错，看了几个issue换成类似的环境还是报错，应该打包依赖问题但是确实没找到原因   idea下直接启动tabby没问题能写到neo4j..

# 环境
win10 jdk1.8.341
neo4j 密码都正确

编译
```
gradlew.bat bootJar
```
后同目录放入config文件夹和jars下的jar包
![image](https://user-images.githubusercontent.com/30001685/204081594-0eec563d-1449-4fe4-9a15-f3d11825c96c.png)

# 错误提示
```
2022-11-26 17:16:58.771  WARN 6992 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'app': Unsatisfied dependency expressed through field 'analyser'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analyser': Unsatisfied dependency expressed through field 'dataContainer'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataContainer': Unsatisfied dependency expressed through field 'rulesContainer'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rulesContainer' defined in URL [jar:file:/C:/Users/Administrator/Downloads/tabby-master/build/libs/tabby-1.1.1.RELEASE.jar!/BOOT-INF/classes!/tabby/core/container/RulesContainer.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [tabby.core.container.RulesContainer]: Constructor threw exception; nested exception is java.io.FileNotFoundException: Sink File Not Found
2022-11-26 17:16:58.773  INFO 6992 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-11-26 17:16:58.777  INFO 6992 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-11-26 17:16:58.791  INFO 6992 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-11-26 17:16:58.810  INFO 6992 --- [           main] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-11-26 17:16:58.881 ERROR 6992 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'app': Unsatisfied dependency expressed through field 'analyser'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analyser': Unsatisfied dependency expressed through field 'dataContainer'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataContainer': Unsatisfied dependency expressed through field 'rulesContainer'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rulesContainer' defined in URL [jar:file:/C:/Users/Administrator/Downloads/tabby-master/build/libs/tabby-1.1.1.RELEASE.jar!/BOOT-INF/classes!/tabby/core/container/RulesContainer.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [tabby.core.container.RulesContainer]: Constructor threw exception; nested exception is java.io.FileNotFoundException: Sink File Not Found
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1413) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.6.jar!/:5.3.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar!/:2.4.5]
        at tabby.App.main(App.java:36) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_341]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_341]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_341]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_341]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tabby-1.1.1.RELEASE.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [tabby-1.1.1.RELEASE.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tabby-1.1.1.RELEASE.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [tabby-1.1.1.RELEASE.jar:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'analyser': Unsatisfied dependency expressed through field 'dataContainer'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataContainer': Unsatisfied dependency expressed through field 'rulesContainer'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rulesContainer' defined in URL [jar:file:/C:/Users/Administrator/Downloads/tabby-master/build/libs/tabby-1.1.1.RELEASE.jar!/BOOT-INF/classes!/tabby/core/container/RulesContainer.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [tabby.core.container.RulesContainer]: Constructor threw exception; nested exception is java.io.FileNotFoundException: Sink File Not Found
```

**Comment by wh1t3p1g** [comment]
看错误是rules下面没有knowledge规则库
