### ISSUE TITLE
无法打开文件GRAPHDB_PUBLIC_METHODS.csv

### ISSUE THREAD

**Issue by INT2ECALL** [wh1t3p1g/tabby#51]
环境：jdk1.8.0_341，neo4j desktop 5.3

无法打开文件 csv 文件报错：
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) [spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) [spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.7.7.jar!/:2.7.7]
        at tabby.App.main(App.java:28) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_341]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_341]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_341]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_341]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tabby.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [tabby.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tabby.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [tabby.jar:na]
Caused by: org.springframework.dao.InvalidDataAccessResourceUsageException: Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.io.IOException: Cannot open file D:\var\lib\neo4j\import\GRAPHDB_PUBLIC_METHODS.csv for reading.; Error code 'Neo.ClientError.Procedure.ProcedureCallFailed'; nested exception is org.neo4j.driver.exceptions.ClientException: Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.io.IOException: Cannot open file D:\var\lib\neo4j\import\GRAPHDB_PUBLIC_METHODS.csv for reading.
```

**Comment by wh1t3p1g** [comment]
配置文件里`tabby.cache.isDockerImportPath` 改成`false`

**Comment by Boogipop** [comment]
我才看到这东西，我还在说为什么出错了

**Comment by INT2ECALL** [comment]
可以了，谢谢师傅
