### ISSUE TITLE
分析大量class时gc overhead limit exceeded问题。

### ISSUE THREAD

**Issue by Ghost2097221** [wh1t3p1g/tabby#53]
师傅我在分析用友NC的过程中，tabby统计大约加载了一万个class文件，然后分析过程中便会出现的报错，之后减少一部分jar还是会出现同一个错误，而且都是在分析同一个class时出现。

2023-04-03 16:23:21.938 DEBUG 19788 --- [           main] t.c.s.value.SimpleRightValueSwitcher     : Analysis: implRemove done, return to<java.security.Provider: java.lang.Object remove(java.lang.Object)>; <java.security.Provider: java.lang.Object remove(java.lang.Object)>
2023-04-03 16:23:21.938 DEBUG 19788 --- [           main] tabby.core.collector.CallGraphCollector  : com.ibm.db2.jcc.am.km b
2023-04-03 16:23:21.938 DEBUG 19788 --- [           main] tabby.core.collector.CallGraphCollector  : org.postgresql.ds.jdbc23.AbstractJdbc23ConnectionPoolDataSource getPooledConnection
2023-04-03 16:23:41.982 ERROR 19788 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOfRange(Arrays.java:3664) ~[na:1.8.0_341]
        at java.lang.String.<init>(String.java:207) ~[na:1.8.0_341]
        at java.lang.StringBuilder.toString(StringBuilder.java:413) ~[na:1.8.0_341]
        at soot.SootMethod.getSubSignatureImpl(SootMethod.java:734) ~[soot-4.4.0-SNAPSHOT.jar!/:na]
        at soot.SootMethod.getSignature(SootMethod.java:684) ~[soot-4.4.0-SNAPSHOT.jar!/:na]
        at soot.SootMethodRefImpl.getSignature(SootMethodRefImpl.java:172) ~[soot-4.4.0-SNAPSHOT.jar!/:na]
        at tabby.core.switcher.value.SimpleRightValueSwitcher.caseInvokeExpr(SimpleRightValueSwitcher.java:104) ~[classes!/:na]
        at tabby.core.switcher.value.SimpleRightValueSwitcher.caseVirtualInvokeExpr(SimpleRightValueSwitcher.java:34) ~[classes!/:na]
        at soot.jimple.internal.AbstractVirtualInvokeExpr.apply(AbstractVirtualInvokeExpr.java:81) ~[soot-4.4.0-SNAPSHOT.jar!/:na]
        at tabby.core.switcher.stmt.SimpleStmtSwitcher.caseAssignStmt(SimpleStmtSwitcher.java:50) ~[classes!/:na]
        at soot.jimple.internal.JAssignStmt.apply(JAssignStmt.java:217) ~[soot-4.4.0-SNAPSHOT.jar!/:na]
        at tabby.core.toolkit.PollutedVarsPointsToAnalysis.flowThrough(PollutedVarsPointsToAnalysis.java:120) ~[classes!/:na]
        at tabby.core.toolkit.PollutedVarsPointsToAnalysis.flowThrough(PollutedVarsPointsToAnalysis.java:30) ~[classes!/:na]
        at soot.toolkits.scalar.FlowAnalysis.flowThrough(FlowAnalysis.java:583) ~[soot-4.4.0-SNAPSHOT.jar!/:na]
        at soot.toolkits.scalar.FlowAnalysis.doAnalysis(FlowAnalysis.java:547) ~[soot-4.4.0-SNAPSHOT.jar!/:na]
        at soot.toolkits.scalar.ForwardFlowAnalysis.doAnalysis(ForwardFlowAnalysis.java:46) ~[soot-4.4.0-SNAPSHOT.jar!/:na]
        at tabby.core.toolkit.PollutedVarsPointsToAnalysis.doAnalysis(PollutedVarsPointsToAnalysis.java:106) ~[classes!/:na]
        at tabby.core.toolkit.PollutedVarsPointsToAnalysis.makeDefault(PollutedVarsPointsToAnalysis.java:191) ~[classes!/:na]
        at tabby.core.switcher.Switcher.doMethodAnalysis(Switcher.java:65) ~[classes!/:na]
        at tabby.core.collector.CallGraphCollector.collect(CallGraphCollector.java:54) ~[classes!/:na]
        at tabby.core.scanner.CallGraphScanner.collect(CallGraphScanner.java:51) ~[classes!/:na]
        at tabby.core.scanner.CallGraphScanner.run(CallGraphScanner.java:38) ~[classes!/:na]
        at tabby.core.Analyser.runSootAnalysis(Analyser.java:132) ~[classes!/:na]
        at tabby.core.Analyser.run(Analyser.java:91) ~[classes!/:na]
        at tabby.App.lambda$run$0(App.java:46) ~[classes!/:na]
        at tabby.App$$Lambda$915/638486177.run(Unknown Source) ~[na:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) ~[spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) ~[spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.7.jar!/:2.7.7]
        at tabby.App.main(App.java:28) ~[classes!/:na]

**Comment by wh1t3p1g** [comment]
看起来是内存溢出了
1. 先看看把内存调大一点是否会出现这个问题
2. 如果还是 OOM , 在 system.json 里面把这个函数加为 ignore 类型，类似下面的规则
```json
{"name": "com.seeyon.ctp.common.parser.BytesEncodingDetect", "rules":[
    {"function": "initialize_frequencies", "type": "ignore", "vul": "", "actions":{}, "polluted":[], "signatures":[]}
  ]},
```
