### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by Und3r1ine** [wh1t3p1g/tabby#66]
错误内容
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: java.lang.IllegalArgumentException: target not exists!
        at tabby.config.GlobalConfiguration.initConfig(GlobalConfiguration.java:144)
        at tabby.App.main(App.java:27)
        ... 8 more
```

**Comment by wh1t3p1g** [comment]
配置文件里的待分析目录不存在

**Comment by Und3r1ine** [comment]
修改配置文件中的这一项是吗
tabby.build.target                        = cases/commons-collections-3.1.jar

**Comment by wh1t3p1g** [comment]
是的，其他配置参考[配置](https://github.com/wh1t3p1g/tabby/blob/master/doc/Tabby%20%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E4%BB%8B%E7%BB%8D.md)

**Comment by Und3r1ine** [comment]
ok,thanks
