### ISSUE TITLE
无法打开GRAPHDB_PUBLIC_METHODS.csv

### ISSUE THREAD

**Issue by zoceanyq** [wh1t3p1g/tabby#67]
环境 macm1 jdk1.8.0.311 neo4j是用docker运行的
一直报错说找不到这个文件GRAPHDB_PUBLIC_METHODS.csv
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) [spring-boot-2.7.7.jar!/:2.7.7]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) [spring-boot-2.7.7.jar!/:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.7.7.jar!/:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.7.7.jar!/:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.7.7.jar!/:2.7.7]
	at tabby.App.main(App.java:28) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_381]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_381]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_381]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_381]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tabby.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [tabby.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tabby.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [tabby.jar:na]
Caused by: org.springframework.dao.InvalidDataAccessResourceUsageException: Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.io.IOException: Cannot open file /Users/oc4an/Documents/web/tabby/output/dev/GRAPHDB_PUBLIC_METHODS.csv for reading.; Error code 'Neo.ClientError.Procedure.ProcedureCallFailed'; nested exception is org.neo4j.driver.exceptions.ClientException: Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.io.IOException: Cannot open file /Users/oc4an/Documents/web/tabby/output/dev/GRAPHDB_PUBLIC_METHODS.csv for reading.
但是我文件夹里面确实是有这个文件的
<img width="719" alt="image" src="https://github.com/wh1t3p1g/tabby/assets/97746429/cbae681f-0238-41d7-a7cd-99890527e5e1">
我本地的配置文件的tabby.cache.isDockerImportPath值就是flase

**Comment by wh1t3p1g** [comment]
用docker的话，tabby.cache.isDockerImportPath=true
