### ISSUE TITLE
运行App.java报错

### ISSUE THREAD

**Issue by ilikeoyt** [wh1t3p1g/tabby#68]
师傅能帮忙看看这种报错是什么原因吗？
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) [spring-boot-2.7.7.jar:2.7.7]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) [spring-boot-2.7.7.jar:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.7.7.jar:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.7.7.jar:2.7.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.7.7.jar:2.7.7]
	at tabby.App.main(App.java:28) [main/:na]
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Unsupported api 589824
	at tabby.core.Analyser.runSootAnalysis(Analyser.java:146) ~[main/:na]
	at tabby.core.Analyser.run(Analyser.java:91) ~[main/:na]
	at tabby.App.lambda$run$0(App.java:46) [main/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) [spring-boot-2.7.7.jar:2.7.7]
	... 5 common frames omitted
Caused by: java.lang.IllegalArgumentException: Unsupported api 589824
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:70) ~[asm-7.1.jar:7.1]
	at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:57) ~[asm-7.1.jar:7.1]
	at soot.asm.SootClassBuilder.<init>(SootClassBuilder.java:83) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:67) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:274) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.SootResolver.bringToHierarchy(SootResolver.java:243) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.SootResolver.bringToSignatures(SootResolver.java:313) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.SootResolver.bringToBodies(SootResolver.java:353) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.SootResolver.processResolveWorklist(SootResolver.java:190) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.SootResolver.resolveClass(SootResolver.java:155) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.Scene.tryLoadClass(Scene.java:992) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at soot.Scene.loadBasicClasses(Scene.java:1833) ~[soot-4.4.0-SNAPSHOT.jar:na]
	at tabby.core.Analyser.runSootAnalysis(Analyser.java:116) ~[main/:na]
	... 8 common frames omitted

**Comment by wh1t3p1g** [comment]
这个报错全吗

**Comment by ilikeoyt** [comment]
全的，就这些报错

**Comment by wh1t3p1g** [comment]
之前没有遇到过这种分析，可以提供一下复现报错的jar
