### ISSUE TITLE
报错，请教大佬什么原因

### ISSUE THREAD

**Issue by MountainCui25** [wh1t3p1g/tabby#73]
# 报错栈：
2023-12-15 15:43:14.867  INFO 31400 --- [           main] tabby.core.container.DataContainer       : Save cache to CSV.
2023-12-15 15:43:16.755  INFO 31400 --- [           main] tabby.core.container.DataContainer       : Save cache to CSV. DONE!
2023-12-15 15:43:16.755  INFO 31400 --- [           main] tabby.core.Analyser                      : Start to save cache.
2023-12-15 15:43:16.757  INFO 31400 --- [           main] tabby.core.container.DataContainer       : Save methods to Neo4j.
2023-12-15 15:43:18.502 ERROR 31400 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) [spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752) [spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.7.7.jar!/:2.7.7]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.7.7.jar!/:2.7.7]
        at tabby.App.main(App.java:32) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_391]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_391]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_391]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_391]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tabby.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [tabby.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tabby.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [tabby.jar:na]
Caused by: org.springframework.dao.PermissionDeniedDataAccessException: The client is unauthorized due to authentication failure.; Error code 'Neo.ClientError.Security.Unauthorized'; nested exception is org.neo4j.driver.exceptions.AuthenticationException: The client is unauthorized due to authentication failure.
        at org.springframework.data.neo4j.core.Neo4jPersistenceExceptionTranslator.translateImpl(Neo4jPersistenceExceptionTranslator.java:107) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.neo4j.core.Neo4jPersistenceExceptionTranslator.translateExceptionIfPossible(Neo4jPersistenceExceptionTranslator.java:83) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient.potentiallyConvertRuntimeException(DefaultNeo4jClient.java:233) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient.access$600(DefaultNeo4jClient.java:62) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:461) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at java.util.Optional.flatMap(Optional.java:241) ~[na:1.8.0_391]
        at org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getSingleResult(Neo4jTemplate.java:1114) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.neo4j.repository.query.Neo4jQueryExecution$DefaultQueryExecution.execute(Neo4jQueryExecution.java:53) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.neo4j.repository.query.AbstractNeo4jQuery.execute(AbstractNeo4jQuery.java:94) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.7.6.jar!/:2.7.6]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.7.6.jar!/:2.7.6]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:160) ~[spring-data-commons-2.7.6.jar!/:2.7.6]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139) ~[spring-data-commons-2.7.6.jar!/:2.7.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:81) ~[spring-data-commons-2.7.6.jar!/:2.7.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.24.jar!/:5.3.24]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.24.jar!/:5.3.24]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.24.jar!/:5.3.24]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.24.jar!/:5.3.24]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at com.sun.proxy.$Proxy104.loadMethodRefFromCSV(Unknown Source) ~[na:na]
        at tabby.dal.neo4j.service.MethodService.importMethodRef(MethodService.java:25) ~[classes!/:na]
        at tabby.core.container.DataContainer.save2Neo4j(DataContainer.java:380) ~[classes!/:na]
        at tabby.core.container.DataContainer$$FastClassBySpringCGLIB$$5e064fdd.invoke(<generated>) ~[classes!/:na]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.24.jar!/:5.3.24]
        at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704) ~[spring-aop-5.3.24.jar!/:5.3.24]
        at tabby.core.container.DataContainer$$EnhancerBySpringCGLIB$$5b32fa1d.save2Neo4j(<generated>) ~[classes!/:na]
        at tabby.core.Analyser.save(Analyser.java:173) ~[classes!/:na]
        at tabby.core.Analyser.run(Analyser.java:105) ~[classes!/:na]
        at tabby.App.lambda$run$0(App.java:48) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768) [spring-boot-2.7.7.jar!/:2.7.7]
        ... 13 common frames omitted
Caused by: org.neo4j.driver.exceptions.AuthenticationException: The client is unauthorized due to authentication failure.
        at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:111) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
        at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:62) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
        at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:47) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
        at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:34) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
        at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:39) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient$DelegatingQueryRunner.run(DefaultNeo4jClient.java:147) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient$RunnableStatement.runWith(DefaultNeo4jClient.java:219) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:454) ~[spring-data-neo4j-6.3.6.jar!/:6.3.6]
        ... 46 common frames omitted
        Suppressed: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database terminated. Please ensure that your database is listening on the correct host and port and that you have compatible encryption settings both on Neo4j server and driver. Note that the default encryption setting has changed in Neo4j 4.0.
                at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:48) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:42) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.async.inbound.ChannelErrorHandler.channelInactive(ChannelErrorHandler.java:67) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:411) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:376) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_391]
        Suppressed: org.neo4j.driver.internal.util.ErrorUtil$InternalExceptionCause: null
                at org.neo4j.driver.internal.util.ErrorUtil.newNeo4jError(ErrorUtil.java:64) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.async.inbound.InboundMessageDispatcher.handleFailureMessage(InboundMessageDispatcher.java:107) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.messaging.common.CommonMessageReader.unpackFailureMessage(CommonMessageReader.java:75) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.messaging.common.CommonMessageReader.read(CommonMessageReader.java:53) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:81) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.async.inbound.InboundMessageHandler.channelRead0(InboundMessageHandler.java:37) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.async.inbound.MessageDecoder.channelRead(MessageDecoder.java:42) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[neo4j-java-driver-4.4.11.jar!/:4.4.11-7d3fdc18543dae49c0c337b2885771b4f38a288d]
                at java.lang.Thread.run(Thread.java:750) ~[na:1.8.0_391]

# 我的配置文件内容：
# need to modify
tabby.build.enable                        = true
tabby.load.enable                         = true

tabby.build.target                        = E:\\RR\\202312\\tabby-master\\cases\\kafka
tabby.build.libraries                     = E:\\RR\\202312\\tabby-master\\cases\\kafka
tabby.build.mode                          = gadget
tabby.output.directory                    = ./output/dev

# debug
tabby.debug.details                       = false

# jdk settings
tabby.build.isJDKProcess                  = true
tabby.build.withAllJDK                    = false
tabby.build.excludeJDK                    = false
tabby.build.isJDKOnly                     = false

# dealing fatjar
tabby.build.checkFatJar                   = true

# pointed-to analysis
tabby.build.isFullCallGraphCreate         = true
tabby.build.thread.timeout                = 2
tabby.build.isNeedToCreateIgnoreList      = false

# db settings
tabby.cache.isDockerImportPath            = false

tabby.neo4j.username                      = neo4j
tabby.neo4j.password                      = admin888
tabby.neo4j.url                           = bolt://127.0.0.1:7687

# 开启debug
tabby.debug.details                   = true
tabby.debug.inner.details             = true

**Comment by wh1t3p1g** [comment]
看报错是neo4j 密码错了

**Comment by wh1t3p1g** [comment]
看报错是neo4j 密码错了

**Comment by MountainCui25** [comment]
多谢大佬，解决了，看起来密码只能设为password，我设为其他的就会报这个错

**Comment by m4ra7h0n** [comment]
我发现，只有5.3.0版本的数据库能用，5.1.0以及最新版的5.15.0都不能用。试了好几个版本终于跑通了

**Comment by wh1t3p1g** [comment]
> 我发现，只有5.3.0版本的数据库能用，5.1.0以及最新版的5.15.0都不能用。试了好几个版本终于跑通了

不会啊，是不是没有配置对
