### ISSUE TITLE
windows下使用--isSaveOnly报错

### ISSUE THREAD

**Issue by d1nfinite** [wh1t3p1g/tabby#9]
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-05-18 14:55:22.911 ERROR 26148 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:822) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar!/:2.4.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar!/:2.4.5]
        at tabby.App.main(App.java:43) [classes!/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_271]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_271]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_271]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_271]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tabby-1.1.0.RELEASE.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [tabby-1.1.0.RELEASE.jar:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tabby-1.1.0.RELEASE.jar:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [tabby-1.1.0.RELEASE.jar:na]
Caused by: org.springframework.dao.InvalidDataAccessResourceUsageException: Failed to invoke procedure `apoc.periodic.iterate`: Caused by: java.net.UnknownHostException: H; Error code 'Neo.ClientError.Procedure.ProcedureCallFailed'
        at org.springframework.data.neo4j.core.Neo4jPersistenceExceptionTranslator.translateImpl(Neo4jPersistenceExceptionTranslator.java:105) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
        at org.springframework.data.neo4j.core.Neo4jPersistenceExceptionTranslator.translateExceptionIfPossible(Neo4jPersistenceExceptionTranslator.java:91) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient.potentiallyConvertRuntimeException(DefaultNeo4jClient.java:174) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient.access$400(DefaultNeo4jClient.java:55) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
        at org.springframework.data.neo4j.core.DefaultNeo4jClient$DefaultRecordFetchSpec.one(DefaultNeo4jClient.java:289) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
        at java.util.Optional.flatMap(Optional.java:241) ~[na:1.8.0_271]
        at org.springframework.data.neo4j.core.Neo4jTemplate$DefaultExecutableQuery.getSingleResult(Neo4jTemplate.java:661) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
        at org.springframework.data.neo4j.repository.query.Neo4jQueryExecution$DefaultQueryExecution.execute(Neo4jQueryExecution.java:53) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
        at org.springframework.data.neo4j.repository.query.AbstractNeo4jQuery.execute(AbstractNeo4jQuery.java:85) ~[spring-data-neo4j-6.0.8.jar!/:6.0.8]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:131) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-data-commons-2.4.8.jar!/:2.4.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.6.jar!/:5.3.6]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.6.jar!/:5.3.6]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.6.jar!/:5.3.6]
        at com.sun.proxy.$Proxy82.loadMethodRefFromCSV(Unknown Source) ~[na:na]
        at tabby.dal.neo4j.service.MethodService.importMethodRef(MethodService.java:23) ~[classes!/:na]
        at tabby.core.container.DataContainer.save2Neo4j(DataContainer.java:279) ~[classes!/:na]
        at tabby.core.Analyser.save(Analyser.java:136) ~[classes!/:na]
        at tabby.core.Analyser.run(Analyser.java:49) ~[classes!/:na]
        at tabby.App.lambda$run$0(App.java:97) [classes!/:na]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) [spring-boot-2.4.5.jar!/:2.4.5]
        ... 13 common frames omitted

2021-05-18 14:55:22.917  INFO 26148 --- [           main] org.neo4j.driver.Driver                  : Closing driver instance 1620823990
2021-05-18 14:55:22.920  INFO 26148 --- [           main] org.neo4j.driver.ConnectionPool          : Closing connection pool towards 127.0.0.1:7687
2021-05-18 14:55:23.135  INFO 26148 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2021-05-18 14:55:23.141  INFO 26148 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2021-05-18 14:55:23.235  INFO 26148 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

- 系统: Windows10
- Java: 1.8_271

**Comment by d1nfinite** [comment]
本地neo4j是可以正常连接的，默认端口，用户名neo4j，密码password

**Comment by d1nfinite** [comment]
apoc插件也安装了

**Comment by weichao-csu** [comment]
I had the same problem

**Comment by wh1t3p1g** [comment]
@d1nfinite @weichao-csu hello，你们先确定一下现在用的版本是不是最新的版本（自己build）
https://github.com/wh1t3p1g/tabby/commit/4b19f597a312e70add1d4afd68230655f67e337d

**Comment by weichao-csu** [comment]
> 
> 
> @d1nfinite @weichao-csu hello，你们先确定一下现在用的版本是不是最新的版本（自己build）
> [4b19f59 ](https://github.com/wh1t3p1g/tabby/commit/4b19f597a312e70add1d4afd68230655f67e337d)

你好，我下载的1.1.0版本，在win平台重新build，在分析jar包的时候就会报出错误，不知你是否在win平台使用过，还是只在MAC OS上面使用过

**Comment by wh1t3p1g** [comment]
> > @d1nfinite @weichao-csu hello，你们先确定一下现在用的版本是不是最新的版本（自己build）
> > [4b19f59 ](https://github.com/wh1t3p1g/tabby/commit/4b19f597a312e70add1d4afd68230655f67e337d)
> 
> 你好，我下载的1.1.0版本，在win平台重新build，在分析jar包的时候就会报出错误，不知你是否在win平台使用过，还是只在MAC OS上面使用过

当前应该是有师傅在win下面跑过了，分析是没问题的。最新版修复了win下导入的问题。
分析jar时的错误可以贴一下我看看

**Comment by weichao-csu** [comment]
我是下载下来直接用idea build，然后分析例子代码，在ubantu上面和win上面都是会报一样的错误，和第一个师傅的问题好像是一样的
`Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-05-21 14:51:37.930 ERROR 9077 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:822) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar!/:2.4.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar!/:2.4.5]
	at tabby.App.main(App.java:42) [classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tabby-1.1.0-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [tabby-1.1.0-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tabby-1.1.0-SNAPSHOT.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [tabby-1.1.0-SNAPSHOT.jar:na]
Caused by: java.lang.ArithmeticException: / by zero
	at tabby.core.scanner.CallGraphScanner.collect(CallGraphScanner.java:72) ~[classes!/:na]
	at tabby.core.scanner.CallGraphScanner.run(CallGraphScanner.java:58) ~[classes!/:na]
	at tabby.core.Analyser.runSootAnalysis(Analyser.java:96) ~[classes!/:na]
	at tabby.core.Analyser.run(Analyser.java:67) ~[classes!/:na]
	at tabby.App.lambda$run$0(App.java:90) [classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) [spring-boot-2.4.5.jar!/:2.4.5]
	... 13 common frames omitted
`

**Comment by weichao-csu** [comment]
我好像找不到问题了 ~_~

**Comment by wh1t3p1g** [comment]
> 我是下载下来直接用idea build，然后分析例子代码，在ubantu上面和win上面都是会报一样的错误，和第一个师傅的问题好像是一样的
> `Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2021-05-21 14:51:37.930 ERROR 9077 --- [ main] o.s.boot.SpringApplication : Application run failed
> 
> java.lang.IllegalStateException: Failed to execute CommandLineRunner
> at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:822) [spring-boot-2.4.5.jar!/:2.4.5]
> at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:803) [spring-boot-2.4.5.jar!/:2.4.5]
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:346) [spring-boot-2.4.5.jar!/:2.4.5]
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340) [spring-boot-2.4.5.jar!/:2.4.5]
> at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) [spring-boot-2.4.5.jar!/:2.4.5]
> at tabby.App.main(App.java:42) [classes!/:na]
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171]
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171]
> at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171]
> at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [tabby-1.1.0-SNAPSHOT.jar:na]
> at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [tabby-1.1.0-SNAPSHOT.jar:na]
> at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [tabby-1.1.0-SNAPSHOT.jar:na]
> at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [tabby-1.1.0-SNAPSHOT.jar:na]
> Caused by: java.lang.ArithmeticException: / by zero
> at tabby.core.scanner.CallGraphScanner.collect(CallGraphScanner.java:72) ~[classes!/:na]
> at tabby.core.scanner.CallGraphScanner.run(CallGraphScanner.java:58) ~[classes!/:na]
> at tabby.core.Analyser.runSootAnalysis(Analyser.java:96) ~[classes!/:na]
> at tabby.core.Analyser.run(Analyser.java:67) ~[classes!/:na]
> at tabby.App.lambda$run$0(App.java:90) [classes!/:na]
> at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:819) [spring-boot-2.4.5.jar!/:2.4.5]
> ... 13 common frames omitted
> `

上一个错误应该用最新版的导入是没问题的。
当前发的错误好像不太详细，看不出来是什么原因造成的。

**Comment by weichao-csu** [comment]
> 
> 
> > 我是下载下来直接用idea build，然后分析例子代码，在ubantu上面和win上面都是会报一样的错误，和第一个师傅的问题好像是一样的 `启动ApplicationContext时出错。  要显示条件报告，请在启用“调试”的情况下重新运行您的应用程序。 
> > 2021-05-21 14：51：37.930错误9077 --- [main] osboot.SpringApplication：应用程序运行失败 
> > java.lang.IllegalStateException：无法执行CommandLineRunner 
> > 在org.springframework.boot.SpringApplication.callRunner（SpringApplication.java:822）上[spring-boot-2.4.5.jar！/：2.4.5] 
> > 在org.springframework.boot.SpringApplication.callRunners（SpringApplication.java:803）上[spring-boot-2.4.5.jar！/：2.4.5] 
> > 在org.springframework.boot.SpringApplication.run（SpringApplication.java:346）上[spring-boot-2.4.5.jar！/：2.4.5] 
> > 在org.springframework.boot.SpringApplication.run（SpringApplication.java:1340）上[spring-boot-2.4.5.jar！/：2.4.5] 
> > 在org.springframework.boot.SpringApplication.run（SpringApplication.java:1329）上[spring-boot-2.4.5.jar！/：2.4.5] 
> > 在tabby.App.main（App.java:42）[classes！/：na] 
> > 在sun.reflect.NativeMethodAccessorImpl.invoke0（本机方法）〜[na：1.8.0_171] 
> > 在sun.reflect.NativeMethodAccessorImpl.invoke（NativeMethodAccessorImpl.java:62）〜[na：1.8.0_171] 
> > 在sun.reflect.DelegatingMethodAccessorImpl.invoke（DelegatingMethodAccessorImpl.java:43）〜[na：1.8.0_171] 
> > 在java.lang.reflect.Method.invoke（Method.java:498）〜[na：1.8.0_171] 
> > 在org.springframework.boot.loader.MainMethodRunner.run（MainMethodRunner.java:49）[tabby-1.1.0-SNAPSHOT.jar：na] 
> > 在org.springframework.boot.loader.Launcher.launch（Launcher.java:108）[tabby-1.1.0-SNAPSHOT.jar：na] 
> > 在org.springframework.boot.loader.Launcher.launch（Launcher.java:58）[tabby-1.1.0-SNAPSHOT.jar：na] 
> > 在org.springframework.boot.loader.JarLauncher.main（JarLauncher.java:88）[tabby-1.1.0-SNAPSHOT.jar：na] 
> > 造成原因：java.lang.ArithmeticException：/被零 
> > 在tabby.core.scanner.CallGraphScanner.collect（CallGraphScanner.java:72）〜[classes！/：na] 
> > 在tabby.core.scanner.CallGraphScanner.run（CallGraphScanner.java:58）〜[classes！/：na] 
> > 在tabby.core.Analyser.runSootAnalysis（Analyser.java:96）〜[classes！/：na] 
> > 在tabby.core.Analyser.run（Analyser.java:67）〜[classes！/：na] 
> > 在tabby.App.lambda $ run $ 0（App.java:90）[classes！/：na] 
> > 在org.springframework.boot.SpringApplication.callRunner（SpringApplication.java:819）上[spring-boot-2.4.5.jar！/：2.4.5] 
> > ...省略了13个通用框架 
> > `
> 
> 上一个错误应该用最新版的导入是没问题的。
> 当前发的错误好像不太详细，看不出来是什么原因造成的。

Caused by: java.lang.ArithmeticException: / by zero
	at tabby.core.scanner.CallGraphScanner.collect(CallGraphScanner.java:72) ~[classes!/:na]
根据这里看好像是.scanner.CallGraphScanner.collect（）这个函数出现的问题，应该是除0了,不知道是不是我的实验代码有问题，看看师傅能否帮忙解决，现在ubantu上面导入完全没有问题，就是分析的时候会报出这样的错误

**Comment by wh1t3p1g** [comment]
@weichao-csu 模0的错误解决了 2333 分析的量太小了https://github.com/wh1t3p1g/tabby/commit/2d97ed9edac69b83a365944f7cf278d42412e342
