### ISSUE TITLE
运行出错ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AirSkye** [wh1t3p1g/tabby#91]
```shell
java -jar -Xmx16g tabby.jar 
 ___________   __       _______   _______  ___  ___
("     _   ") /""\     |   _  "\ |   _  "\|"  \/"  |
 )__/  \\__/ /    \    (. |_)  :)(. |_)  :)\   \  /
    \\_ /   /' /\  \   |:     \/ |:     \/  \\  \/
    |.  |  //  __'  \  (|  _  \\ (|  _  \\  /   /
    \:  | /   /  \\  \ |: |_)  :)|: |_)  :)/   /
     \__|(___/    \___)(_______/ (_______/|___/
                      v1.3.2
              Happy Hunting Bugs! XD
         https://github.com/wh1t3p1g/tabby

2024-04-09T02:01:46.834Z  INFO 10273 --- [           main] tabby.App                                : Starting App using Java 17 with PID 10273 (/root/tabby/tabby.jar started by root in /root/tabby)
2024-04-09T02:01:46.844Z  INFO 10273 --- [           main] tabby.App                                : The following 1 profile is active: "default"
2024-04-09T02:02:06.006Z  INFO 10273 --- [           main] tabby.core.container.RulesContainer      : load 58 rules success!
2024-04-09T02:02:08.787Z  INFO 10273 --- [           main] tabby.config.AsyncConfiguration          : Open 10 size for thread pool tabby-collector
2024-04-09T02:02:08.812Z  INFO 10273 --- [           main] tabby.config.AsyncConfiguration          : Open 5 size for thread pool tabby-saver
2024-04-09T02:02:09.856Z  INFO 10273 --- [           main] tabby.App                                : Started App in 28.998 seconds (process running for 31.983)
2024-04-09T02:02:09.897Z  INFO 10273 --- [           main] tabby.App                                : Target java.home: /root/jdk-17
2024-04-09T02:02:10.827Z  INFO 10273 --- [           main] tabby.core.Analyser                      : Get 3 JDK dependencies
2024-04-09T02:02:10.827Z  INFO 10273 --- [           main] tabby.core.Analyser                      : Try to collect all targets
2024-04-09T02:02:10.828Z  INFO 10273 --- [           main] tabby.core.Analyser                      : Target: source/
2024-04-09T02:02:10.833Z  INFO 10273 --- [           main] tabby.common.utils.FileUtils             : Create directory /root/tabby/temp/tabby_ZFi89ba3b10-39dd-44fa-b821-f27d930f81d3 success!
2024-04-09T02:02:11.044Z  INFO 10273 --- [           main] tabby.core.Analyser                      : Load basic classes
2024-04-09T02:02:12.811Z  INFO 10273 --- [           main] tabby.core.Analyser                      : Load dynamic classes
2024-04-09T02:02:12.814Z  INFO 10273 --- [           main] tabby.core.Analyser                      : Total analyse 1 targets.
2024-04-09T02:02:12.818Z  INFO 10273 --- [           main] tabby.core.Analyser                      : Target 1, Dependencies 4
2024-04-09T02:02:12.818Z  INFO 10273 --- [           main] tabby.core.scanner.ClassInfoScanner      : Start to collect 1 targets' class information.
2024-04-09T02:02:13.822Z ERROR 10273 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at tabby.core.Analyser.runSootAnalysis(Analyser.java:133)
	at tabby.core.Analyser.run(Analyser.java:85)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:352)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:713)
	at tabby.core.Analyser$$SpringCGLIB$$0.run(<generated>)
	at tabby.App.lambda$run$1(App.java:73)
	at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:798)
	at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83)
	at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60)
	at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:806)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:797)
	at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:782)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:782)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:341)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1358)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1347)
	at tabby.App.main(App.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91)
	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53)
	at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at tabby.common.utils.JavaVersionUtils.getLocalVersion(JavaVersionUtils.java:22)
	at tabby.common.utils.JavaVersionUtils.isAtLeast(JavaVersionUtils.java:38)
	at tabby.common.utils.SemanticUtils.getTargetClasses(SemanticUtils.java:556)
	at tabby.core.scanner.ClassInfoScanner.loadAndExtract(ClassInfoScanner.java:59)
	at tabby.core.scanner.ClassInfoScanner.run(ClassInfoScanner.java:40)
	at tabby.core.Analyser.runSootAnalysis(Analyser.java:117)
	... 36 common frames omitted
```
环境信息
```shell
uname -a
Linux ecs-qm8j3 4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

java -version
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

tree
|-- cases
|   |-- jackson
|   |   `-- 2.11.4
|   |       |-- jackson-core-2.11.4.jar
|   |       `-- jackson-databind-2.11.4.jar
|   `-- jdk1.8_201
|       `-- rt.jar
|-- config
|   |-- db.properties
|   `-- settings.properties
|   `-- tabby-path-finder-1.1.jar
|-- logs
|   |-- debug.log
|   `-- warn.log
|-- output
|   |-- dev
|-- rules
|   |-- basicClasses.json
|   |-- commonJars.json
|   |-- sinks.json
|   |-- system.json
|   `-- tags.json
|-- run.sh
|-- source
|   `-- jackson-annotations-2.11.4.jar
|-- tabby-vul-finder.jar
|-- tabby.jar
```
配置文件
```properties
# need to modify
tabby.build.target                        = source/
tabby.build.libraries                     = libs
tabby.build.mode                          = gadget
tabby.output.directory                    = ./output/dev

# debug
tabby.debug.details                       = false
tabby.debug.print.current.methods         = true

# jdk settings
tabby.build.useSettingJRE                 = false
tabby.build.isJRE9Module                  = true
#tabby.build.javaHome                      = /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
tabby.build.javaHome                      = /root/jdk-17/bin/java
tabby.build.isJDKProcess                  = false
tabby.build.withAllJDK                    = false
tabby.build.isJDKOnly                     = false

# dealing fatjar
tabby.build.checkFatJar                   = true

# pointed-to analysis
tabby.build.isFullCallGraphCreate         = false
tabby.build.thread.timeout                = 2
tabby.build.method.timeout                = 5
tabby.build.isNeedToCreateIgnoreList      = false
tabby.build.timeout.forceStop             = false
tabby.build.isNeedToDealNewAddedMethod    = true
```

**Comment by wh1t3p1g** [comment]
感谢提交，可以试一下最新的commit

**Comment by AirSkye** [comment]
可以了，感谢师傅
